// The Betrayed Will / وصية الغدر
// Copyright (c) 2026. All rights reserved.

#include "Characters/TBWCharacterLook.h"
#include "Components/MeshComponent.h"
#include "Materials/MaterialInterface.h"
#include "Materials/MaterialInstanceDynamic.h"
#include "UObject/ConstructorHelpers.h"
#include "TBW.h"

namespace
{
	// Generated by tools/ue_python/build_east_wing.py. Parameters: BaseColor,
	// Roughness, Metallic. If the level has never been built on this machine it
	// will not exist, and tinting is simply skipped.
	static const TCHAR* MasterPath = TEXT("/Game/TBW/Art/Blockout/M_TBW_Blockout.M_TBW_Blockout");

	UMaterialInterface* LoadMaster()
	{
		static TWeakObjectPtr<UMaterialInterface> Cached;
		static bool bTried = false;
		if (Cached.IsValid())
		{
			return Cached.Get();
		}
		if (bTried)
		{
			return nullptr;
		}
		bTried = true;
		UMaterialInterface* Master =
			LoadObject<UMaterialInterface>(nullptr, MasterPath, nullptr, LOAD_NoWarn | LOAD_Quiet);
		if (!Master)
		{
			UE_LOG(LogTBW, Warning,
				TEXT("Blockout master material missing (%s). Characters keep their default "
					 "materials and will all look alike. Run tools\\BUILD_LEVEL.cmd once."),
				MasterPath);
			return nullptr;
		}
		Cached = Master;
		return Master;
	}
}

void FTBWCharacterLook::Apply(UMeshComponent* Mesh, const FLinearColor& Tint, float Roughness)
{
	if (!Mesh)
	{
		return;
	}
	UMaterialInterface* Master = LoadMaster();
	if (!Master)
	{
		return;
	}

	const int32 Slots = FMath::Max(Mesh->GetNumMaterials(), 1);
	for (int32 Index = 0; Index < Slots; ++Index)
	{
		UMaterialInstanceDynamic* Dynamic = UMaterialInstanceDynamic::Create(Master, Mesh);
		if (!Dynamic)
		{
			continue;
		}
		Dynamic->SetVectorParameterValue(TEXT("BaseColor"), Tint);
		Dynamic->SetScalarParameterValue(TEXT("Roughness"), Roughness);
		Dynamic->SetScalarParameterValue(TEXT("Metallic"), 0.f);
		Mesh->SetMaterial(Index, Dynamic);
	}
}

float FTBWCharacterLook::Jitter(FName Seed)
{
	const uint32 Hash = GetTypeHash(Seed);
	return static_cast<float>(Hash % 1000) / 1000.f;
}
